/**
 *  This file was autogenerated with sequelize-cli
 *  after running "npx sequelize init:models"
 */
'use strict'

const fs = require('fs')
const path = require('path')
const Sequelize = require('sequelize')
const basename = path.basename(__filename)
const db = {}

const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: './database.sqlite3',
})

// Import all models and add them to the db object
fs.readdirSync(__dirname)
  .filter((file) => {
    return (
      file.indexOf('.') !== 0 &&
      file !== basename &&
      file.slice(-3) === '.js' &&
      file.indexOf('.test.js') === -1
    )
  })
  .forEach((file) => {
    const model = require(path.join(__dirname, file))(
      sequelize,
      Sequelize.DataTypes,
    )
    db[model.name] = model
  })

// Run associations on all models
Object.keys(db).forEach((modelName) => {
  if (db[modelName].associate) {
    db[modelName].associate(db)
  }
})

// Add sequelize instance to the db object
db.sequelize = sequelize

module.exports = db
